// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urrctozczprwjfyqogmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVycmN0b3pjenByd2pmeXFvZ213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTY2NjAsImV4cCI6MjA3Mjc5MjY2MH0.ib1XeIo9k1QPlZzOT3utA_SEz39t8JoS97X1e9YVoHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});